apiVersion: storage.azure.crossplane.io/v1alpha3
kind: Account
metadata:
  name: "${{ values.name }}"
  labels:
    example: "true"
spec:
  resourceGroupName: "${{ values.project }}"
  storageAccountSpec:
    kind: Storage
    location: "${{ values.region }}"
    sku:
      name: Standard_LRS
      tier: Standard
    tags:
      application: crossplane
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    namespace: crossplane-system

---

{% if values.container %}
apiVersion: storage.azure.crossplane.io/v1alpha3
kind: Container
metadata:
  name: "${{ values.container }}"
  labels:
    storage_account: "${{ values.name }}"
spec:
  writeConnectionSecretToRef:
    name: "${{ values.container }}-container-secret"
    namespace: crossplane-system
  # Azure containers read their credentials from an Account, not a Provider. We
  # use the providerRef field to specify which Account to read credentials from.
  providerConfigRef:
    name: "${{ values.name }}"
{% endif %}
