apiVersion: backstage.io/v1alpha1
kind: Resource 
metadata:
  name: "${{ values.name }}-Storage-Account"
#  annotations:
#    backstage.io/techdocs-ref: dir:.
  description: "Azure storage account"
  labels:
    resource-type: account
#    region: "${{ values.region}}"
#    Creator: "Creator is - ${{ values.user}}"
#    Team: "Team managing resource is - ${{ values.owner}}" 
  tags:
    - azure
    - storage
    - crossplane
    - "${{ values.region}}"

#    - "Created by: ${{ values.user}}"
  links:
    - url: https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview
      title: Azure storage account docs
#      icon: github
      type: Documentation
spec:
  type: storage-account
  lifecycle: experimental
  owner: "${{ values.owner }}"
  system: "${{ values.project }}"
  dependsOn:
  - "${{ values.project }}"

