{% if values.container %}
apiVersion: backstage.io/v1alpha1
kind: Resource 
metadata:
  name: "${{ values.container }}-blob-storage"
#  annotations:
#    backstage.io/techdocs-ref: dir:.
  description: "Blob storage for storing data"
  labels:
    resource-type: storage 
  tags:
    - azure
    - storage
    - blob 
    - bucket
  links:
    - url: https://azure.microsoft.com/en-us/products/storage/blobs
      title: Azure Blob storage docs
#      icon: github
      type: Documentation
spec:
  type: blob-storage
  lifecycle: experimental
  owner: "${{ values.user.metadata.name }}"
  system: "${{ values.owner.metadata.name }}"
  dependsOn:
  - "resource:${{ values.name }}-Storage-Account"
{% endif %}