# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: az-storage
  title: Azure Blob Storage Dev
  description: Create azure bucket for object storage for development environment
spec:
  #owner: team
  type: Resource 

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Creating a Storage Account with a container 
      required:
        - name
        - region
        - container
      properties:
        name:
          title: Name
          type: string
          description: Unique name for storage account
          ui:help: 'Hint: Name must be very unique, add random numbers at as suffix to created name e.g tonystarksa-4834'
          maxLength: 15
          ui:autofocus: true
        region:
          title: Region
          type: string
          description: Unique name for storage account
          default: "West US 2"
          enum:
            - "West US 2"
            - "East US 1"
          enumNames:
            - 'West US 2'
            - 'East US 1'
        container:
          title: Container name
          type: string
          description: Name of container with a maximum length of 15 characters
          maxLength: 15
        owner:
          title: Owner
          type: string
          description: Owner of the Resource
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          default: 'github.com?repo=backstage-gitops&owner=giddy87' 
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base-sa
      name: Fetch Base SA
      action: fetch:template
      targetPath: fetched-data
      #replace: true 
      #-${{ parameters.name }}.yaml
      input:
        url: https://github.com/giddy87/backstage-gitops/blob/main/base/
        values:
          name: ${{ parameters.name }}
          region: ${{ parameters.region }}
          project-name: ${{ parameters.name }}
          container: ${{parameters.container  }}
#    - id: fetch-base-container
#      name: Fetch Base Container
#      action: fetch:template
#      targetPath: ./container.yaml
      #-${{ parameters.container }}.yaml
#      input:
#        url: https://github.com/giddy87/backstage-gitops/blob/main/base/azure-sa-container.yaml
#        values:
#          name: ${{ parameters.name }}
#          container: ${{ parameters.container }}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        branchName: ${{ parameters.name  }}
        title: Create Azure storage account ${{ parameters.name }} and container ${{ parameters.container }}
        description: Azure storage account and container PR
        sourcePath: result
        targetPath: .
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}

#    - id: register
#      name: Register
#      action: catalog:register
#      input:
#        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
#        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
#  output:
#    links:
#      - title: Repository
#        url: ${{ steps['publish'].output.remoteUrl }}
#      - title: Open in catalog
#        icon: catalog
#        entityRef: ${{ steps['register'].output.entityRef }}
