# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: az-storage
  title: Azure Storage Account
  description: Create azure storage account for object storage for development environment
spec:
  #owner: team
  type: Resource 

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Creating a Storage Account with a container 
      required:
        - project
        - name
        - region
      properties:
        name:
          title: Name
          type: string
          description: Unique name for storage account
          ui:help: 'Hint: Azure storage account names must be globally unique, add random numbers as suffix in addition to name choice up to 15 characters max e.g tonystarksa-4834'
          maxLength: 15
          ui:autofocus: true
        env:
          title: Environment
          description: Create Storage account for Local testing or Project
          type: string
          enum:
            - Local
            - Project 
          enumNames:
            - Local
            - Project
        project: 
          title: Project
          type: string
          description: Name of the Project storage account is being created for
        region:
          title: Region
          type: string
          description: Unique name for storage account
          default: "UK South"
          enum:
            - "West Europe"
            - "North Europe"
            - "UK South"
            - "East US"
            - "East US 2"
            - "West US 2"
            - "West US 3"
            - "France Central"
            - "Central US"
          enumNames:
            - 'West Europe'
            - 'North Europe'
            - 'UK South'
            - 'East US'
            - 'East US 2'
            - 'West US 2'
            - 'West US 3'
            - 'France Central'
            - 'Central US'
        container:
          title: Default Container name (Optional)
          type: string
          description: Name of container with a maximum length of 15 characters
          maxLength: 15
        owner:
          title: Owner
          type: string
          description: Owner of the Resource
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
    - title: Choose a Repo
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          default: 'github.com?repo=backstage-gitops&owner=giddy87' 
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base-sa
      name: Fetch Base SA
      action: fetch:template      
      #replace: true 
      #-${{ parameters.name }}.yaml
      input:
        #templateFileExtension: ".yaml"
        #cookiecutterCompat: true
        targetPath: results
        url: https://github.com/giddy87/backstage-gitops/blob/main/base/azure-storage-account/
        values:
          name: ${{ parameters.name }}
          region: ${{ parameters.region }}
          project-name: ${{ parameters.name }}
          container: ${{ parameters.container  }}
    - id: Rename-files
      name: Add prefix to resource name
      action: fs:rename
      input:
        files:
#          - from: ./results/azure-sa-container.yaml
#            to: ./results/${{ parameters.name }}-azure-sa-container.yaml
          - from: ./results/azure-sa.yaml
            to: ./results/${{ parameters.name }}-azure-sa.yaml
          - from: ./results/catalog-info.yaml
            to: ./results/${{ parameters.name }}-catalog-info.yaml
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        branchName: ${{ parameters.name  }}
        title: Create Azure storage account ${{ parameters.name }} and container ${{ parameters.container }}
        description: Azure storage account and container PR
        sourcePath: results
        targetPath: ./resources
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: "https://github.com/giddy87/backstage-gitops/blob/${{ parameters.name }}"
        catalogInfoPath: '/resources/${{ parameters.name }}-catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
#  output:
#    links:
#      - title: Repository
#        url: ${{ steps['publish'].output.remoteUrl }}
#      - title: Open in catalog
#        icon: catalog
#        entityRef: ${{ steps['register'].output.entityRef }}
