
apiVersion: backstage.io/v1alpha1
kind: Resource 
metadata:
  name: "logs67-blob-storage"
#  annotations:
#    backstage.io/techdocs-ref: dir:.
  description: "Blob storage for storing data"
  labels:
    resource-type: storage 
  tags:
    - azure
    - storage
    - blob 
    - bucket
  links:
    - url: https://azure.microsoft.com/en-us/products/storage/blobs
      title: Azure Blob storage docs
#      icon: github
      type: Documentation
spec:
  type: storage
  lifecycle: experimental
  owner: dev-team
  system: azure
  dependsOn:
  - "resource:test67-Storage-Account"
#