
apiVersion: backstage.io/v1alpha1
kind: Resource 
metadata:
  name: "point22457-Blob-container"
#  annotations:
#    backstage.io/techdocs-ref: dir:.
  description: "Blob storage for storing data"
  labels:
    resource-type: storage 
    region: "UK South"
  tags:
    - azure
    - storage
    - blob 
    - bucket
  links:
    - url: https://azure.microsoft.com/en-us/products/storage/blobs
      title: Azure Blob storage docs
#      icon: github
      type: Documentation
spec:
  type: blob-storage
  lifecycle: experimental
  owner: "user:colette.brock"
  system: "system:redbox"
  dependsOn:
  - "resource:point22457-Storage-Account"
