apiVersion: backstage.io/v1alpha1
kind: Resource 
metadata:
  name: "post12-Storage-Account"
#  annotations:
#    backstage.io/techdocs-ref: dir:.
  description: "Azure storage account"
  labels:
    resource-type: account
  tags:
    - azure
    - storage
    - crossplane
    - "Created by: user:nigel.manning" 
  links:
    - url: https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview
      title: Azure storage account docs
#      icon: github
      type: Documentation
spec:
  type: storage-account
  lifecycle: experimental
  owner: "team-c"
  system: "system:redbox"

