apiVersion: backstage.io/v1alpha1
kind: Resource 
metadata:
  name: "test26-storage"
#  annotations:
#    backstage.io/techdocs-ref: dir:.
  description: Blob storage for storing data
  labels:
    resource-type: storage account
  tags:
    - azure
    - storeage Account
    - crossplane 
  links:
    - url: https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview
      title: Azure storage account docs
#      icon: github
      type: Documentation
spec:
  type: storage
  lifecycle: experimental
  owner: dev-team
  system: azure
