apiVersion: storage.azure.crossplane.io/v1alpha3
kind: Container
metadata:
  name: "${{ values.container }}"
  labels:
    storage_account: "${{ values.name }}"
spec:
  writeConnectionSecretToRef:
    name: "${{ values.container }}-container-secret"
    namespace: crossplane-system
  # Azure containers read their credentials from an Account, not a Provider. We
  # use the providerRef field to specify which Account to read credentials from.
  providerConfigRef:
    name: "${{ values.name }}"
